potions:
- potion: Artless
  effects:
  - [potion.digSpeed, 100, 200]
- potion: Thin
  effects:
  - [potion.hunger, 0, 1500]
- potion: Bungling
  effects:
  - [potion.jump, 10, 200]
- potion: Smooth
  effects:
  - [potion.resistance, 0, 600]
- potion: Sparkling
  effects:
  - [potion.waterBreathing, 0, 1500]
- potion: Rank
  effects:
  - [potion.blindness, 0, 300]
- potion: Gross
  effects:
  - [potion.confusion, 0, 300]
- potion: Stinky
  effects:
  - [potion.digSlowDown, 0, 300]

# http:, , www.minecraftwiki.net, wiki, Potions#Unused_Potions
damageValues:
    Clear: [6,7]
    Diffuse: [11]
    Artless: [13]
    Thin: [14,15]
    Bungling: [22,23]
    Smooth: [27]
    Suave: [29]
    Debonair: [30,31]
    Charming: [38,39]
    Refined: [43]
    Cordial: [45]
    Sparkling: [46,47]
    Potent: [48]
    Rank: [54,55]
    Acrid: [59]
    Gross: [61]
    Stinky: [62,63]

