verbose: true

potions:
- potion: Clear
  effects:
  - [potion.digSpeed, 1, 9600]
  - [potion.weakness, 0, 1800]

- potion: Diffuse
  effects:
  - [potion.moveSpeed, 10, 900]
  - [potion.blindness, 1, 450]

- potion: Artless
  effects:
  - [potion.digSpeed, 100, 200]

- potion: Thin
  effects:
  - [potion.hunger, 0, 1500]

- potion: Bungling
  effects:
  - [potion.jump, 10, 200]

- potion: Smooth
  effects:
  - [potion.resistance, 0, 600]

- potion: Suave
  effects:
  - [potion.moveSpeed, 0, 3600]
  - [potion.damageBoost, 0, 3600]

- potion: Debonair
  effects:
  - [potion.damageBoost, 0, 9600]
  - [potion.hunger, 0, 4800]

- potion: Charming
  effects:
  - [potion.moveSpeed, 3, 1800]

- potion: Refined
  effects:
  - [potion.moveSpeed, 2, 3000]
  - [potion.regeneration, 0, 3000]
  - [potion.harm, 2, 0]

- potion: Cordial
  effects:
  - [potion.digSlowDown, 0, 300]

- potion: Sparkling
  effects:
  - [potion.waterBreathing, 0, 1500]

- potion: Potent
  effects:
  - [potion.moveSpeed, 0, 1200]
  - [potion.digSpeed, 1, 1200]
  - [potion.damageBoost, 0, 1200]
  - [potion.heal, 2, 0]
  - [potion.jump, 1, 1200]
  - [potion.resistance, 1, 1200]
  - [potion.fireResistance, 1, 1200]
  - [potion.waterBreathing, 1, 1200]
  - [potion.hunger, 0, 1200]

- potion: Rank
  effects:
  - [potion.blindness, 0, 300]

- potion: Acrid
  effects:
  - [potion.confusion, 0, 300]
  - [potion.blindness, 0, 150]
  - [potion.poison, 0, 50]

- potion: Gross
  effects:
  - [potion.confusion, 0, 300]

- potion: Stinky
  effects:

# http://www.minecraftwiki.net/wiki/Potions#Unused_Potions
damageValues:
    Clear: [6,7]
    Diffuse: [11]
    Artless: [13]
    Thin: [14,15]
    Bungling: [22,23]
    Smooth: [27]
    Suave: [29]
    Debonair: [30,31]
    Charming: [38,39]
    Refined: [43]
    Cordial: [45]
    Sparkling: [46,47]
    Potent: [48]
    Rank: [54,55]
    Acrid: [59]
    Gross: [61]
    Stinky: [62,63]

